log-files-directory: /Users/iurii/Downloads/kraken
#blockchain: hoodi
blockchain: mainnet
log-parser: standard
#log-parser: kraken
target-slot: 12298720 # attestations example
#target-slot: 999423 # sync-committee example
