#log-files-directory: /Users/iurii/Downloads/target
log-files-directory: /Users/iurii/Downloads/target
blockchain: hoodi
#blockchain: mainnet
log-format: standard
#log-format: external
analyze-committee-duty: true
analyze-proposer-duty: false
target-slot: 1026357 # attestations example
#target-slot: 999423 # sync-committee example
