benchmark:
  duration: 15m
  network: mainnet
  server:
    port: 8080

  consensus:
  # Can be a single address or a collection of addresses. Both formats are supported:
  # `address: http://127.0.0.1:8080` and `address: [http://127.0.0.1:8080, http://127.0.0.2:8080]`.
    address: []
    metrics: 
      client:
        enabled: true
      latency:
        enabled: true
      peers:
        enabled: true
      attestation:
        enabled: true

  execution:
  # Can be a single address or a collection of addresses. Both formats are supported:
  # `address: http://127.0.0.1:8080` and `address: [http://127.0.0.1:8080, http://127.0.0.2:8080]`.
    address: []
    metrics: 
      peers:
        enabled: true

  ssv:
    address: 
    metrics: 
      peers:
        enabled: true
      connections:
        enabled: true
  
  infrastructure:
    metrics:
      cpu:
        enabled: true
      memory:
        enabled: true

analyzer:
  log-files-directory:
  operators: []
  cluster: false