benchmark:
  duration: 15m
  network: mainnet
  server:
    port: 8080

  consensus:
    address: 
    metrics: 
      client:
        enabled: true
      latency:
        enabled: true
      peers:
        enabled: true
      attestation:
        enabled: true

  execution:
    address: 
    metrics: 
      peers:
        enabled: true

  ssv:
    address: 
    metrics: 
      peers:
        enabled: true
      connections:
        enabled: true
  
  infrastructure:
    metrics:
      cpu:
        enabled: true
      memory:
        enabled: true

analyzer:
  log-file-path: example-path
  operators: []
  cluster: true