name: "Docker reusable workflow"

on:
  workflow_call:
    inputs:
      with-push:
        description: "determines if to push docker image to an image registry, otherwise will just build"
        default: false
        type: boolean
        required: false
      image-tag:
        description: "docker image tag. Defaults to 'latest'"
        default: "latest"
        type: string
        required: false

env:  
  IMAGE_ARCHITECTURES: linux/amd64,linux/arm64
  IMAGE_REGISTRY: ghcr.io
  DOCKERFILE_PATH: build/Dockerfile
  IMAGE_DESCRIPTION: |
    This Docker image is a CLI tool for evaluating the health and severity of various SSV client related metrics over time.

jobs:
  docker:
    name: Build/Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    env:
      IMAGE_TAG: ${{ inputs.image-tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.IMAGE_ARCHITECTURES }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: ${{ inputs.with-push }}
          platforms: ${{ env.IMAGE_ARCHITECTURES }}
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}:latest
          outputs: |
            type=image,name=target,annotation-index.org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
