name: Main branch workflow

on:
  push:
    branches:
      - main

env:  
  IMAGE_ARCHITECTURES: linux/amd64,linux/arm64
  IMAGE_REGISTRY: ghcr.io
  DOCKERFILE_PATH: build/Dockerfile
  IMAGE_DESCRIPTION: |
    This Docker image is a CLI tool for evaluating the health and severity of various SSV client related metrics over time.

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  docker-build-push:
    uses: ./.github/workflows/docker.yml
    permissions:
      id-token: write
      packages: write
      contents: read
    needs: publish-release
    with:
      with-push: true
      image-tag: ${{ needs.publish-release.outputs.new_tag }}