name: Feature branch workflow

on:
  pull_request:
    branches:
      - main

# Rapid successive pushes to a PR cancel the outdated in-flight run.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.repo.full_name }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  go-checks:
    uses: ./.github/workflows/go.yml
    permissions:
      contents: read

  docker-build:
    uses: ./.github/workflows/docker.yml
    needs: go-checks
    permissions:
      id-token: write
      packages: write
      contents: read
    with:
      with-push: false
      image-architectures: linux/amd64
